# Generated by Django 5.0 on 2024-01-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('mrs', models.IntegerField()),
                ('systolic', models.IntegerField()),
                ('distolic', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('bmi', models.IntegerField()),
                ('cholestrol', models.IntegerField()),
                ('tos', models.IntegerField()),
                ('risk', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
