# Generated by Django 5.0 on 2024-01-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='risk',
        ),
    ]
