# Generated by Django 5.0.1 on 2024-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ramadandate_iqamahadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqamahadjustment',
            name='prayer_name',
            field=models.CharField(choices=[('fajr', 'Fajr'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=50),
        ),
    ]
